name: graduation_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  cookie_jar: ^4.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/electrical/
    - assets/images/painting/
    - assets/images/cleaning/
    - assets/images/plumbing/
    - assets/images/air/
    - assets/images/carpentry/
    - assets/images/top/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
